web:
  build: .
  command: python fetch.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app:z
  links:
    - db

db:
  image: postgres
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: database
  ports:
      - 5432:5432
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  restart: always
