web:
  build: .
  command: flask run
  environment:
    FLASK_ENV: development
  ports:
    - 5000:5000
  volumes:
    - .:/app:z
  links:
    - db
    - redis

db:
  image: postgres
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: database
  ports:
      - 5432:5432
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  restart: always

redis:
  image: redis:alpine
  ports:
    - 6379:6379
  restart: always
