"""change zone attrs

Revision ID: 5b57bc4a9889
Revises: 85532d25e34b
Create Date: 2020-10-12 19:29:04.692166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b57bc4a9889'
down_revision = '85532d25e34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'geo_shape')
    op.drop_column('zone', 'geopoint_2d')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('geopoint_2d', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('zone', sa.Column('geo_shape', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
