"""change zone attrs

Revision ID: 9ac3c9832a02
Revises: 5b57bc4a9889
Create Date: 2020-10-12 19:30:11.569984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ac3c9832a02'
down_revision = '5b57bc4a9889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('shape', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('zone', 'response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('zone', 'shape')
    # ### end Alembic commands ###
